- name: Stop and disable systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Deploy resolv.conf file
  vars:
    address: "{{ hostvars[groups['dns_servers'][0]]['ansible_default_ipv4']['address'] }}"
  ansible.builtin.template:
    src: ../templates/resolv_conf.j2
    dest: /etc/resolv.conf