- name: Install package nginx
  ansible.builtin.apt:
    name: nginx

- name: Deploy the nginx config
  ansible.builtin.template:
    src: ../files/default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: Force nginx restart if changed
  meta: flush_handlers

- name: Start and enable the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Install prometheus nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Start and enable prometheus nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true

- name: Add CNAME records hor hosts to DNS master
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    zone: "{{ domain_name }}"
    record: "{{ item.alias }}"
    type: CNAME
    value: "{{ item.target }}"
    state: present
  loop:
    - { alias: "nginx-1", target: "{{ groups['nginx'][0] }}" }
    - { alias: "nginx-2", target: "{{ groups['nginx'][1] }}" }
    - { alias: "nginx-3", target: "{{ groups['nginx'][2] }}" }
