- name: Install package nginx
  ansible.builtin.apt:
    name: nginx
  notify: Restart Nginx

- name: Start and enable the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy the nginx config
  ansible.builtin.template:
    src: ../files/default.j2
    dest: /etc/nginx/sites-enabled/default
    # validate: nginx -t -c %s
  notify: Restart Nginx