- name: Install HAProxy package
  ansible.builtin.apt:
    name: haproxy

- name: Deploy HAProxy config
  ansible.builtin.template:
    src: ../templates/haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Start and enable HAProxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Install prometheus haproxy exporter
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter

- name: Deploy prometheus haproxy exporter config
  ansible.builtin.template:
    src: ../templates/prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart prometheus haproxy exporter

- name: Start and enable prometheus haproxy exporter
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true

- name: Add CNAME record to DNS master
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    zone: amogus.sus
    record: "{{ item.alias }}"
    type: CNAME
    value: "{{ item.target }}"
    state: present
  loop:
    - { alias: "lb-1", target: "{{ groups['haproxy'][0] }}" }
    - { alias: "lb-2", target: "{{ groups['haproxy'][1] }}" }
