- name: Import influxdb repo key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present

- name: Add influxdb repo
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/debian stable main stable main
    state: present

- name: Ensure InfluxDB user exists
  ansible.builtin.user:
    name: influxdb
    state: present
    create_home: yes

- name: Install influxdb
  ansible.builtin.apt:
    name: influxdb

- name: Deploy influxdb config
  ansible.builtin.template:
    src: ../templates/influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Restart influxdb

- name: Start and enable influxdb
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true

- name: Download telegraf
  ansible.builtin.apt:
    name: telegraf

- name: Deploy telegraf config
  ansible.builtin.template:
    src: ../templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Start and enable telegraf
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true

- name: Install InfluxDB exporter
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/prometheus-influx-exporter
    mode: 0755
    owner: prometheus
    group: prometheus

- name: Deploy exporter service config
  ansible.builtin.template:
    src: ../templates/influxdb-exporter-service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify: Restart influxdb exporter

- name: Start and enable influxdb exporter
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: true

- name: Create directory for dumping influx backup files
  ansible.builtin.file:
    name: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: '0744'

- name: Deploy cron backup schedule
  ansible.builtin.template:
    src: ../templates/influxdb-backup-cron.j2
    dest: /etc/cron.d/influxdb-backup
  notify: Restart cron

- name: Add CNAME record to DNS master
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    zone: "{{ domain_name }}"
    record: "{{ item.alias }}"
    type: CNAME
    value: "{{ item.target }}"
    state: present
  loop:
    - { alias: "influxdb", target: "{{ groups['influx'][0] }}" }
