---
- name: Initial setup
  hosts: all
  roles:
    - init

- name: Dns server
  hosts: dns_servers
  roles:
    - bind

- name: Name resolution
  hosts: all
  roles:
    - resolv

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx

- name: Prometheus
  hosts: prometheus
  roles:
    - prometheus
    - nginx

- name: Grafana
  hosts: grafana
  roles:
    - grafana
    - nginx
