---
- name: Gather facts about all
  hosts: all
  roles:
    - facts
  tags:
    - dns
    - db
    - influx
    - agama
    - keepalived
    - haproxy
    - grafana
    - prometheus
    - agama-scale
    - switchover
    - gather-facts

- name: Initial setup
  hosts: all
  roles:
    - init
  tags:
    - init

- name: Dns server
  hosts: dns_servers
  roles:
    - bind
  tags:
    - dns

- name: Name resolution
  hosts: dns_servers
  roles:
    - resolv
  tags:
    - resolv
    - dns

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - db
    - switchover

- name: Influxdb
  hosts: influx
  roles:
    - influxdb
  tags:
    - influx

- name: Web server
  hosts: web_servers
  roles:
    - docker
    - agama
    - nginx
  tags:
    - agama
    - switchover
    - agama-scale

- name: Agama client
  hosts: agama_client
  roles:
    - agama_client
  tags:
    - agama-client


- name: keepalived
  hosts: keepalived
  roles:
    - keepalived
  tags:
    - keepalived

- name: HAProxy
  hosts: haproxy
  roles:
    - haproxy
  tags:
    - haproxy
    - agama-scale

- name: Prometheus
  hosts: prometheus
  roles:
    - prometheus
    - nginx
  tags:
    - prometheus

- name: Grafana
  hosts: grafana
  roles:
    - docker
    - grafana
    - nginx
  tags:
    - grafana
