---
- name: Initial setup
  hosts: all
  roles:
    - init
    - docker
  tags:
    - init

- name: Dns server
  hosts: dns_servers
  roles:
    - bind
  tags:
    - dns

- name: Name resolution
  hosts: all
  roles:
    - resolv
  tags:
    - resolv

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags:
    - db
    - switchover

- name: Influxdb
  hosts: influx
  roles:
    - influxdb
  tags:
    - influx

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
    - agama_client
  tags:
    - agama
    - switchover

- name: Prometheus
  hosts: prometheus
  roles:
    - prometheus
    - nginx
  tags:
    - prometheus

- name: Grafana
  hosts: grafana
  roles:
    - grafana
    - nginx
  tags:
    - grafana
