{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL server ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL server mode",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL replica IO thread -- gets changes from remote",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL replica SQL thread -- commit changes to local relay log",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Total Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}