- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Apply zone file
  ansible.builtin.command: rndc reload

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true