- name: Create /opt/agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download files
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - { url: "https://raw.githubusercontent.com/hudolejev/agama/master/agama.py", dest: "/opt/agama/agama.py" }
    - { url: "https://raw.githubusercontent.com/hudolejev/agama/refs/heads/master/Dockerfile", dest: "/opt/agama/Dockerfile" }

- name: Build agama container
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

# - name: Start agama
#   community.docker.docker_container:
#     image: agama
#     name: agama
#     state: started
#     published_ports: '{{ agama_port }}:8000'
#     env:
#       AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
#   no_log: true

- name: Start agama containers
  community.docker.docker_container:
    image: agama
    name: "agama_{{ item }}"
    state: started
    published_ports: "{{ agama_port + item }}:8000"
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  no_log: true
  loop: "{{ range(0, agama_container_count) | list }}"