- name: Install package mysql
  ansible.builtin.apt:
    name: mysql-server
  notify: Restart mysql

- name: Start and enable the mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Override mysql config
  ansible.builtin.template:
    src: ../templates/mysql_config
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
  notify: Restart mysql

- name: Add MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  notify: Restart mysql

- name: Add MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    state: present
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart mysql

- name: Create MySQL user for prometheus exporter
  community.mysql.mysql_user:
    name: 'exporter'
    password: "{{ mysql_exporter_password }}"
    host: "%"
    state: present
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart mysql

- name: Install prometheus_mysql_exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter

- name: Deploy mysql exporter config
  ansible.builtin.template:
    src: ../templates/my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    mode: '0400'
    owner: prometheus
    group: prometheus
  notify: 
    - Restart mysql exporter
    - Start and enable mysql exporter
  no_log: true
