- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Restart influxdb exporter
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
