- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus

- name: Deploy prometheus config
  ansible.builtin.template:
    src: ../templates/prometheus_conf.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus

- name: Deploy prometheus starting config
  vars:
    prometheus_host: "{{ hostvars[groups['prometheus'][0]]['ansible_host'] }}"
    prometheus_port: "{{ hostvars[groups['prometheus'][0]]['ansible_port'] }}"
  ansible.builtin.template:
    src: ../templates/prometheus_start.j2
    dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Start and enable the prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Add CNAME record to DNS master
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    zone: "{{ domain_name }}"
    record: "{{ item.alias }}"
    type: CNAME
    value: "{{ item.target }}"
    state: present
  loop:
    - { alias: "prometheus", target: "{{ groups['prometheus'][0] }}" }
