- name: Install docker
  ansible.builtin.apt:
    name: docker.io

- name: Install python3-docker
  ansible.builtin.apt:
    name: python3-docker

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
