- name: Install bind9
  ansible.builtin.apt:
    name: bind9

- name: Start and Enable bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true

- name: Deploy bind9 config
  ansible.builtin.template:
    src: ../templates/bind_conf.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Deploy master zone file
  ansible.builtin.template:
    src: ../templates/master_zone.j2
    dest: /var/cache/bind/db.{{ domain_name }}
  notify: Apply zone file
