- name: Install bind9
  ansible.builtin.apt:
    name: bind9

- name: Install dnspython
  ansible.builtin.apt:
    name: python3-dnspython

- name: Deploy master zone file
  ansible.builtin.template:
    src: ../templates/master_zone.j2
    dest: /var/cache/bind/db.{{ domain_name }}
    force: false
    mode: "0766"
  notify: 
    - Apply zone file
    - Restart bind9

- name: Deploy reverse zone file
  ansible.builtin.template:
    src: ../templates/ptr_zone.j2
    dest: /var/cache/bind/db.rev
    force: false
    mode: "0766"
  notify: 
    - Apply zone file
    - Restart bind9

- name: Deploy bind9 global options
  ansible.builtin.template:
    src: ../templates/bind_conf.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Deploy bind9 zones config
  ansible.builtin.template:
    src: ../templates/bind_named_conf_local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Check if bind exporter is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/prometheus-bind9-exporter
  register: bind_exporter_stat

- name: Install Bind prometheus exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus-community/bind_exporter/releases/download/v0.6.1/bind_exporter-0.6.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true
    creates: /usr/local/bin/prometheus-bind9-exporter

- name: Copy bind exporter executable to bind
  ansible.builtin.copy:
    src: /tmp/bind_exporter-0.6.1.linux-amd64/bind_exporter
    dest: /usr/local/bin/prometheus-bind9-exporter
    mode: '0755'
    remote_src: true
  when: not bind_exporter_stat.stat.exists

- name: Remove file from temporary location
  ansible.builtin.file:
    path: /tmp/bind_exporter-0.6.1.linux-amd64
    state: absent

- name: Deploy systemd bind9 exporter service config
  ansible.builtin.template:
    src: ../templates/exporter_service_conf.j2
    dest: /etc/systemd/system/prometheus-bind9-exporter.service
  notify: Reload systemd

- name: Start and Enable prometheus-bind9-exporter
  ansible.builtin.service:
    name: prometheus-bind9-exporter
    state: started
    enabled: true

- name: Force bind restart if changed
  meta: flush_handlers

- name: Start and Enable bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true

- name: Add backup server A record
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    zone: "{{ domain_name }}"
    record: "{{ backup_server_name }}"
    type: A
    value: "{{ backup_server_ip }}"
    state: present

- name: Add CNAME record to DNS master
  community.general.nsupdate:
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key }}"
    key_algorithm: "hmac-sha256"
    zone: "{{ domain_name }}"
    record: "{{ item.alias }}"
    type: CNAME
    value: "{{ item.target }}"
    state: present
  loop:
    - { alias: "ns-1", target: "{{ groups['dns_servers'][0] }}" }
    - { alias: "ns-2", target: "{{ groups['dns_servers'][1] }}" }
    - { alias: "ns-3", target: "{{ groups['dns_servers'][2] }}" }
