# - name: Ansible ping module
#   ansible.builtin.ping:
# - name: Create user juri
#   ansible.builtin.user:
#     name: juri
#     create_home: yes

# - name: Create user roman
#   ansible.builtin.user:
#     name: roman
#     create_home: yes

# - name: Put keys into user juri
#   ansible.posix.authorized_key:
#     user: juri
#     state: present
#     key: https://github.com/hudolejev.keys

# - name: Put keys into user roman
#   ansible.posix.authorized_key:
#     user: roman
#     state: present
#     key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install prometheus node on all machines
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Start and enable the prometheus-node-exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Deploy rsyslog config
  ansible.builtin.template:
    src: ../templates/rsyslog.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Start and enable rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true