- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install prometheus node on all machines
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Start and enable the prometheus-node-exporter service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true

- name: Deploy rsyslog config
  ansible.builtin.template:
    src: ../templates/rsyslog.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Start and enable rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Create user for backups
  ansible.builtin.user:
    name: backup
    home: /home/backup
    state: present
    create_home: true
    generate_ssh_key: true
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Add backup server ssh key to known_hosts for user backup
  ansible.builtin.template:
    src: ../templates/known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0644'

- name: Create directory for restoring backups
  ansible.builtin.file:
    name: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0744'

- name: Install duplicity
  ansible.builtin.apt:
    name: duplicity
    state: present
